# Generated by Django 5.2.11 on 2026-03-05 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10, unique=True, verbose_name='Día')),
                ('is_open', models.BooleanField(default=True, verbose_name='Abierto')),
                ('opening_time', models.TimeField(default='09:00', verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(default='17:00', verbose_name='Hora de cierre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Horario de Clínica',
                'verbose_name_plural': 'Horarios de Clínica',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('duration', models.IntegerField(verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('icon', models.CharField(default='💉', max_length=10, verbose_name='Icono emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('specialty', models.CharField(choices=[('general', 'Medicina General'), ('surgery', 'Cirugía'), ('dental', 'Odontología'), ('dermatology', 'Dermatología'), ('cardiology', 'Cardiología'), ('emergency', 'Emergencias')], max_length=20, verbose_name='Especialidad')),
                ('license_number', models.CharField(max_length=50, verbose_name='Número de cédula')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('years_experience', models.IntegerField(verbose_name='Años de experiencia')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('available_days', models.JSONField(default=list, help_text='Lista de días disponibles', verbose_name='Días disponibles')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Hora de fin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vets/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('general', 'Información General'), ('care', 'Cuidado de Mascotas'), ('health', 'Salud y Vacunación'), ('nutrition', 'Nutrición'), ('training', 'Entrenamiento'), ('other', 'Otros')], default='general', max_length=50, verbose_name='Categoría')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo PDF')),
                ('icon', models.CharField(default='📄', max_length=10, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pet_type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], max_length=10, verbose_name='Tipo')),
                ('other_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar tipo')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('age', models.IntegerField(verbose_name='Edad (años)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('vaccination_status', models.CharField(choices=[('updated', 'Al día'), ('pending', 'Pendiente'), ('none', 'Sin vacunas')], default='updated', max_length=10, verbose_name='Estado de vacunación')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias o condiciones médicas')),
                ('friendly_with_people', models.BooleanField(default=True)),
                ('friendly_with_animals', models.BooleanField(default=True)),
                ('nervous_at_vet', models.BooleanField(default=False)),
                ('special_care', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('checkup', 'General Checkup'), ('vaccination', 'Vaccination'), ('dental', 'Dental Cleaning'), ('grooming', 'Grooming'), ('surgery', 'Surgery Consultation'), ('emergency', 'Emergency Visit')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.pet')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
