# Generated by Django 5.2.11 on 2026-03-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_options_appointment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.pet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('checkup', 'Consulta General'), ('vaccination', 'Vacunación'), ('dental', 'Limpieza Dental'), ('grooming', 'Estética'), ('surgery', 'Consulta de Cirugía'), ('emergency', 'Emergencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.CharField(default='bi bi-file-earmark-pdf', max_length=50, verbose_name='Icono Bootstrap'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='bi bi-clipboard-pulse', max_length=50, verbose_name='Icono Bootstrap'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='available_days',
            field=models.JSONField(default=list, verbose_name='Días disponibles'),
        ),
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300, verbose_name='Motivo de consulta')),
                ('symptoms', models.TextField(verbose_name='Síntomas observados')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment', models.TextField(verbose_name='Tratamiento indicado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('weight_at_visit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('next_visit', models.DateField(blank=True, null=True, verbose_name='Próxima visita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='booking.appointment', verbose_name='Cita')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.veterinarian', verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_instructions', models.TextField(verbose_name='Indicaciones generales')),
                ('warnings', models.TextField(blank=True, verbose_name='Advertencias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='booking.medicalconsultation', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dose', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duration', models.CharField(max_length=100, verbose_name='Duración')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Tópico'), ('injectable', 'Inyectable'), ('ophthalmic', 'Oftálmico'), ('otic', 'Ótico'), ('other', 'Otro')], default='oral', max_length=20, verbose_name='Vía de administración')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones específicas')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.medicalprescription', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
