# Generated by Django 5.2.11 on 2026-03-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_pet_age_pet_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la vacuna')),
                ('date', models.DateField(verbose_name='Fecha de aplicación')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='booking.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-date'],
            },
        ),
    ]
