# Generated by Django 5.2.11 on 2026-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='veterinarians', to='booking.service', verbose_name='Servicios que ofrece'),
        ),
    ]
